### ISSUE TITLE
[2.0] Explicit loop parameters are deprecated

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aioredis-py#1002]
The new 2.0 implementation has a number of places where it either takes an explicit `loop` parameter, or passes one to an asyncio function. The need for this was largely removed in Python 3.5.3 (because `get_event_loop` was changed to return the event loop of the current task when called from inside a task), and many functions (such as [wait_for](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for) deprecated the parameter in 3.8 with removal for 3.10. Other functions (like [open_connection](https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection)) didn't deprecate it, but made it optional and documented that it is not needed when called from a coroutine. I wouldn't be surprised if they are deprecated in future.

I would suggest:
(a) eliminating passing the parameter where it is deprecated e.g. wait_for
(b) eliminating passing the parameter where it is unnecessary
(c) eliminating the `loop` argument to the `Connection` constructor and the `_loop` attribute. The finalizer currently uses it, but I've argued in #930 that this is a bad idea.

Let me know if a PR is likely to be looked at.

**Comment by Andrew-Chen-Wang** [comment]
@bmerry Do it! (asyncio is an evolving lib so yea go for it!)
