### ISSUE TITLE
[2.0] Use loop.time() instead of time.time() for health checks

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aioredis-py#1003]
In the 2.0 alpha, health checks are based around `time.time`. Using `asyncio.get_event_loop().time()` has several advantages:
- The default implementation uses a monotonic clock, so it won't go wonky if the system time is changed.
- It sticks to a consistent source of time relative to things like `async_timeout`, which makes mocking out time easier (e.g. with [async-solipsism](https://github.com/bmerry/async-solipsism)).

I'm happy to submit a PR if there is agreement that this is a reasonable change.

**Comment by bmerry** [comment]
I've created https://github.com/andymccurdy/redis-py/pull/1491 against redis-py to have it use monotonic time.

**Comment by Andrew-Chen-Wang** [comment]
I believe we're trying to stick closely to redis-py implementation, so I'll +1 the ref PR to gain a bit more attention for discussion.
