### ISSUE TITLE
[2.0] Replace PubSub.run_in_thread with a coroutine

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aioredis-py#1007]
The port from redis-py brought along PubSub.run_in_thread, and it's been modified to run code on the event loop (some event loop anyway). However, I feel like this is an area where it makes sense to depart from the redis-py API, since users of aioredis will most likely prefer to use asyncio for concurrency rather than threads. It also has zero test coverage, since the one test ported from redis-py is marked as skipped with a note that it is broken.

I would like to suggest replacing it by a coroutine simply called `run` that implements the same logic. Users can then choose to either await it directly (maybe as part of a larger asyncio task that sets up the pubsub) or can use `asyncio.create_task` to launch it asynchronously, and use it with standard asyncio task management tools (such as `Task.cancel`).

If that's acceptable I'll volunteer to make a PR.

**Comment by seandstewart** [comment]
@bmerry -

This is something I debated on doing while I was doing the port. I'm a fan of it and think it makes a lot more sense for the concurrency model.

**Comment by bmerry** [comment]
Implemented in #1014, so closing.
