### ISSUE TITLE
pub/sub 100% CPU utilization

### ISSUE THREAD

**Issue by briankosw** [aio-libs/aioredis-py#1023]
I'm subscribing to a Redis channel using the provided sample code in the documentation. When I run the script, it hits 100% CPU utilization, even when there are no messages being published to the channel. I do plan on horizontal scaling the subscriber to reduce load on each node, but I want to make sure that I don't have any logic error that is over-utilizing the CPU. The following is the code I'm using:

```python
async def pubsub() -> None:
    redis = aioredis.from_url("redis://localhost", decode_responses=True)
    psub = redis.pubsub()

    async def reader(channel: aioredis.client.PubSub):
        while True:
            try:
                async with async_timeout.timeout(1):
                    message = await channel.get_message(
                        ignore_subscribe_messages=True
                    )
                    if message is not None:
                        asyncio.create_task(
                            sio.emit("message", json.dumps(message))
                        )
                    await asyncio.sleep(0)
            except asyncio.TimeoutError:
                pass

    async with psub as p:
        await p.subscribe("tickers")
        await reader(p)
        await p.unsubscribe("tickers")

    await psub.close()

async def main():
    await pubsub()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(main())
    loop.run_forever()
```

**Comment by Andrew-Chen-Wang** [comment]
try ‘asyncio.sleep(0.1)’

**Comment by fr3aker** [comment]
`channel.get_message` immediately returns if no message is available, thus the loop is burning your resources. Add a timeout parameter to avoid this.

**Comment by briankosw** [comment]
> `channel.get_message` immediately returns if no message is available, thus the loop is burning your resources. Add a timeout parameter to avoid this.

Ah that explains it all. Thank you so much!
