### ISSUE TITLE
[2.0] pipeline fails with `AttributeError`

### ISSUE THREAD

**Issue by rad-pat** [aio-libs/aioredis-py#1025]
When trying to use 2.0.0a1, I get an `AttributeError` trying to use a pipeline. It's very easy to replicate with the code below.

```
import asyncio
from aioredis import Redis

async def pipeline_bug():
    r = Redis(
        host='localhost',
        #port=,
        db='1',
        password='***',
        decode_responses=False,
        health_check_interval=30,
        retry_on_timeout=True
    )
    keys = ['somekey']
    p = r.pipeline()
    await p.get(keys[0])
    x = await p.execute()


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(pipeline_bug())
```
`AttributeError: 'Pipeline' object has no attribute 'single_connection_client'`

**Comment by rad-pat** [comment]
Setting `single_connection_client` = False on a `Pipeline` seems to be working ok for me here at the moment

**Comment by abrookins** [comment]
#1029 appears to have fixed this, and the code in this issue now runs without errors.
