### ISSUE TITLE
Is the connection is task / async safe?

### ISSUE THREAD

**Issue by asaff1** [aio-libs/aioredis-py#1026]
Not sure if it's a bug, but for me it's an unexpected behavior.

Run in `python -m asyncio`

```Python
import aioredis
r = await aioredis.create_redis("redis://localhost:6379")

print(await x.revrange("stream1", count=1))  # Works correctly, prints

async def xread():
    print("xread")
    print("xread returned: ", await r.xread("machine:state"))

t = asyncio.get_running_loop().create_task(xread())

print(await x.revrange("stream1", count=1))  # Blocking! Is that expected?
```
It seems like the `xread()` freezes the client for doing any other async work.
 AFAIK `xrange` should never block the caller. Correct?

I checked with other async clients like `aredis` and it does not happen.

Any explanation for that?

**Comment by rsj-ioki** [comment]
I can confirm this for create_redis_pool() also

**Comment by rsj-ioki** [comment]
> Can you try this with the latest beta? `pip install aioredis --pre --upgrade`

Yes working!!!
