### ISSUE TITLE
Misleading doc - Readthedocs points to 2.X documentation

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [aio-libs/aioredis-py#1042]
The latest stable version, the 1.3.1, does not reflect the documentation published on https://aioredis.readthedocs.io/en/latest/ . It seems that the doc is referring to the 2.X.

In addition to that, seems not possible to switch to the documentation of the old version.

How can I navigate the 1.3.1 documentation?

**Comment by Andrew-Chen-Wang** [comment]
@ca-simone-chiorazzo  https://aioredis.readthedocs.io/en/v1.3.1/ Apologies for not updating; it should be merged in #970
