### ISSUE TITLE
Rename redis-py health check message

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [aio-libs/aioredis-py#1065]
https://github.com/aio-libs/aioredis-py/blob/c82fe277a5a6521aa9baacd672dd131313fe1b45/aioredis/client.py#L3873

Should we change this to aioredis-py @seandstewart @abrookins in case someone uses both redis-py and aioredis?

**Comment by abrookins** [comment]
Yeah, we should. Good catch!
