### ISSUE TITLE
hmset_dict missing

### ISSUE THREAD

**Issue by phenobarbital** [aio-libs/aioredis-py#1081]
Hi!

I tried a migration from 1.3+ to 2.0 without success, some methods like hmset_dict are missing, if I try the "Getting Started" example: [(](https://aioredis.readthedocs.io/en/latest/getting-started/#response-decoding)
```
redis = aioredis.from_url("redis://localhost")
await redis.hmset_dict("hash", key1="value1", key2="value2", key3=123)
```

I got this result:
AttributeError: 'Redis' object has no attribute 'hmset_dict'

I'm missing something?

**Comment by seandstewart** [comment]
Hey @phenobarbital - 

The Redis client is now compliant with `redis-py` and no longer has this method. 

You'll need to adapt your code to use [Redis.hmset](https://aioredis.readthedocs.io/en/latest/api/high-level/#aioredis.client.Redis.hmset).

**Comment by phenobarbital** [comment]
Thanks! @seandstewart, I see it, but also, the method Redis.hmset returns "this method has been deprecated" when I used it.
But I'm currently migrated from hmset_dict to hmset without issues.
Thanks again and good job!, I'll be awaiting so much time for this new version compatible with async-await syntax.
