### ISSUE TITLE
Developer requirements conflict

### ISSUE THREAD

**Issue by Olegt0rr** [aio-libs/aioredis-py#1084]
### Input:
```make devel```

### Output:
```
ERROR: Cannot install -r docs/requirements.txt (line 6) and mkdocs-autorefs==0.3.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested mkdocs-autorefs==0.3.0
    mkdocstrings 0.15.2 depends on mkdocs-autorefs<0.3 and >=0.1
```

**Comment by Olegt0rr** [comment]
@abrookins @Andrew-Chen-Wang 
Thanks for fix!

You can avoid this type of bugs via pipe with pip install. If it fails - you'll watch dependabot PR closer

**Comment by Andrew-Chen-Wang** [comment]
@Olegt0rr apologies. Our CI doesn't actually run pip installation for the docs I think. We can probably set up a CI to make sure it doesn't crash later on though (TODO: do it in a separate workflow file such that we can specify to only run if the docs dir has changed).
