### ISSUE TITLE
TypeError: unittest failure in travis 

### ISSUE THREAD

**Issue by atezerjani** [aio-libs/aioredis-py#1090]
I just upgraded the aioredis dependency to 2.0.0 for my application, however the travis build fails with this stacktrace logged:

tox/py37/lib/python3.7/site-packages/aioredis/__init__.py:1: in <module>
    from aioredis.client import Redis, StrictRedis
.tox/py37/lib/python3.7/site-packages/aioredis/client.py:48: in <module>
    from aioredis.lock import Lock
.tox/py37/lib/python3.7/site-packages/aioredis/lock.py:13: in <module>
    class Lock:
.tox/py37/lib/python3.7/site-packages/aioredis/lock.py:241: in Lock
    def release(self) -> Awaitable[NoReturn]:
/opt/python/3.7.1/lib/python3.7/typing.py:251: in inner
    return func(*args, **kwds)
/opt/python/3.7.1/lib/python3.7/typing.py:626: in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
/opt/python/3.7.1/lib/python3.7/typing.py:626: in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
/opt/python/3.7.1/lib/python3.7/typing.py:135: in _type_check
    raise TypeError(f"Plain {arg} is not valid as type argument")
E   TypeError: Plain typing.NoReturn is not valid as type argument

Does anybody know any workaround for it?

**Comment by Andrew-Chen-Wang** [comment]
https://github.com/ipfs-shipyard/py-ipfs-http-client/issues/235#issuecomment-687127566

> It is a bug in python. Newer pythons (>=3.7.2) should be okay with this.

Upgrade your Python version and you're good to go.

**Comment by Andrew-Chen-Wang** [comment]
Closing since I think a correct solution has been provided.
