### ISSUE TITLE
ConnectionError "Too many connections"

### ISSUE THREAD

**Issue by nan-guo** [aio-libs/aioredis-py#1113]
Hello,

I'm trying to migrate my lib from 1.3.1 to 2.0.0 and getting some connection errors `ConnectionError("Too many connections")`.

I created a connection pool with `max_connections = 10`, and I got the connection error if I gather more than 10 coroutines to execute. 

To reproduce:  

max_connections = 2 and 3 concurrent tasks.

```
import asyncio
import aioredis


async def run():
    redis = aioredis.from_url(
        url=f"redis://172.18.0.3:6379/0",
        encoding="utf-8",
        decode_responses=True,
        max_connections=2
    )
    task_1 = asyncio.create_task(redis.ping())
    task_2 = asyncio.create_task(redis.ping())
    task_3 = asyncio.create_task(redis.ping())

    await asyncio.gather([task_1, task_2, task_3])

asyncio.run(run())
```

Expected output:
```
Use 2 connections in the pool to successfully ping 3 tasks.
```

Current output:
```
raise ConnectionError("Too many connections")
```

Compared with v1.x, this is a different behavior. If there is no available connection in the connection pool, will we try to wait for a free connection instead of [raising an exception](https://github.com/aio-libs/aioredis-py/blob/master/aioredis/connection.py#L1395) ?

**Comment by fedej** [comment]
Hi,

 You can use a BlockingConnectionPool to that end

**Comment by nan-guo** [comment]
Good to know, thanks.
