### ISSUE TITLE
aioredis.exceptions.ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTERS`

### ISSUE THREAD

**Issue by miss85246** [aio-libs/aioredis-py#1142]
### Describe the bug

Hi there, I'm trying use `aioredis.sentinel` in my code. I have a cluster created by docker. It's like this:

![image](https://user-images.githubusercontent.com/42527535/135182958-557099b9-d06b-4eb0-bede-4d47ef0bcdda.png)

and then, I use [Redis Sentinel Client](https://aioredis.readthedocs.io/en/latest/examples/#redis-sentinel-client) example code.
but  I got exception :
```
aioredis.exceptions.ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTERS`, 
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002B4ECD45D30>
```

by the way, my firewalld is closed.

### To Reproduce

1. create a redis cluster with docker
2. use this code
```python
import asyncio

import aioredis.sentinel


async def main():
    sentinel_client = aioredis.sentinel.Sentinel(
        [("192.168.3.18", 26379), ("192.168.3.18", 26380), ("192.168.3.18", 26381)])

    master_redis: aioredis.Redis = sentinel_client.master_for("mymaster")
    info = await master_redis.sentinel_master("mymaster")
    print("Master role:", info)


if __name__ == "__main__":
    asyncio.run(main())
```
3. got the exception

### Expected behavior

I'm not  sure

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "E:\Codeing\GitHub\sanic_demo\apps\core\aredis.py", line 16, in <module>
    asyncio.run(main())
  File "C:\Software\Programing\Languages\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Software\Programing\Languages\Python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\Codeing\GitHub\sanic_demo\apps\core\aredis.py", line 11, in main
    info = await master_redis.sentinel_master("mymaster")
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\client.py", line 1061, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\connection.py", line 1359, in get_connection
    await connection.connect()
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\sentinel.py", line 54, in connect
    await self.connect_to(await self.connection_pool.get_master_address())
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\sentinel.py", line 117, in get_master_address
    master_address = await self.sentinel_manager.discover_master(self.service_name)
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\sentinel.py", line 222, in discover_master
    masters = await sentinel.sentinel_masters()
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\client.py", line 1064, in execute_command
    return await self.parse_response(conn, command_name, **options)
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\client.py", line 1080, in parse_response
    response = await connection.read_response()
  File "E:\Codeing\Python\.virtualenvs\sanic_demo\lib\site-packages\aioredis\connection.py", line 868, in read_response
    raise response from None
aioredis.exceptions.ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTERS`, 
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000299A1395D30>
Traceback (most recent call last):
  File "C:\Software\Programing\Languages\Python\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Software\Programing\Languages\Python\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Software\Programing\Languages\Python\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Software\Programing\Languages\Python\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 1
```

### Python Version

```console
$ python --version
3.9.2
```

### aioredis Version

```console
$ python -m pip show aioredis
2.0.0
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bzbzbz** [comment]
I'm seeing this as well, when running a redis and sentinel instance on localhost.    Using the sample code as provided in the ['Recipes' section of the v2 docs](https://aioredis.readthedocs.io/en/latest/examples/#redis-sentinel-client)

Switching back to aioredis v1.3.1 works as far as getting the sentinel setup and determining the master


Python 3.8.8
Redis server v5.0.7

**Comment by miss85246** [comment]
> I'm seeing this as well, when running a redis and sentinel instance on localhost.    Using the sample code as provided in the ['Recipes' section of the v2 docs](https://aioredis.readthedocs.io/en/latest/examples/#redis-sentinel-client)
> 
> Switching back to aioredis v1.3.1 works as far as getting the sentinel setup and determining the master
> 
> 
> Python 3.8.8
> Redis server v5.0.7
> 

All right, can you give me a simple sentinel usage with v1.3 ? I'm not familar with this. thanks 😀

**Comment by bzbzbz** [comment]
@miss85246  The official v1.3.1 docs are probably a good place to start:

https://aioredis.readthedocs.io/en/v1.3.1/sentinel.html

**Comment by bzbzbz** [comment]
At least in my case, I can confirm passing in the master IP and sentinel port when attempting to use aioredis v2, as I'm using the aioredis v2 recipes example as-is.    Oddly, v1.3.1 works fine.   Here's my output from the cli when connecting to the sentinel port:

```bash
me@localhost:~$ redis-cli -h localhost -p 26379 SENTINEL MASTERS
1)  1) "name"
    2) "mymaster"
    3) "ip"
    4) "127.0.0.1"
    5) "port"
    6) "6379"
    7) "runid"
    8) "03f193c5821b7077191f9fa7f8bceb7289395fb4"
    9) "flags"
   10) "master"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "267"
   19) "last-ping-reply"
   20) "267"
   21) "down-after-milliseconds"
   22) "30000"
   23) "info-refresh"
   24) "2000"
   25) "role-reported"
   26) "master"
   27) "role-reported-time"
   28) "369212266"
   29) "config-epoch"
   30) "0"
   31) "num-slaves"
   32) "0"
   33) "num-other-sentinels"
   34) "0"
   35) "quorum"
   36) "2"
   37) "failover-timeout"
   38) "180000"
   39) "parallel-syncs"
   40) "1"
```



Here's the recipe code and traceback, using the latest commit on master 73ae8fb (v2 tagged release produces the same exception):

```python
Python 3.8.8 (default, Feb 24 2021, 03:57:16)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import asyncio
   ...:
   ...: import aioredis.sentinel
   ...:
   ...:
   ...: async def main():
   ...:     sentinel_client = aioredis.sentinel.Sentinel([("localhost", 26379)])
   ...:
   ...:     master_redis: aioredis.Redis = sentinel_client.master_for("mymaster")
   ...:     info = await master_redis.sentinel_master("mymaster")
   ...:     print("Master role:", info)
   ...:
   ...:
   ...: if __name__ == "__main__":
   ...:     asyncio.run(main())
   ...:
---------------------------------------------------------------------------
ResponseError                             Traceback (most recent call last)
<ipython-input-1-42ccdc545fd2> in <module>
     13
     14 if __name__ == "__main__":
---> 15     asyncio.run(main())

~/.local/lib/python3.8/asyncio/runners.py in run(main, debug)
     42         if debug is not None:
     43             loop.set_debug(debug)
---> 44         return loop.run_until_complete(main)
     45     finally:
     46         try:

~/.local/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
    614             raise RuntimeError('Event loop stopped before Future completed.')
    615
--> 616         return future.result()
    617
    618     def stop(self):

<ipython-input-1-42ccdc545fd2> in main()
      8
      9     master_redis: aioredis.Redis = sentinel_client.master_for("mymaster")
---> 10     info = await master_redis.sentinel_master("mymaster")
     11     print("Master role:", info)
     12

~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/client.py in execute_command(self, *args, **options)
   1064         try:
   1065             await conn.send_command(*args)
-> 1066             return await self.parse_response(conn, command_name, **options)
   1067         except (ConnectionError, TimeoutError) as e:
   1068             await conn.disconnect()

~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/client.py in parse_response(self, connection, command_name, **options)
   1080         """Parses a response from the Redis server"""
   1081         try:
-> 1082             response = await connection.read_response()
   1083         except ResponseError:
   1084             if EMPTY_RESPONSE in options:

~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/sentinel.py in read_response(self)
     63     async def read_response(self):
     64         try:
---> 65             return await super().read_response()
     66         except ReadOnlyError:
     67             if self.connection_pool.is_master:

~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/connection.py in read_response(self)
    869
    870         if isinstance(response, ResponseError):
--> 871             raise response from None
    872         return response
    873

ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTER`, `mymaster`,
```

**Comment by miss85246** [comment]
@bzbzbz  @abrookins  thanks for your help, the problem is solved. @abrookins you are right, I can't connect those sentinel and can't run the sentinel master command, that's my fault. When I use this [project](https://github.com/colby/sentinel) to build redis sentinel, It's worked very well. But I still have some minor problems.
I have mapped the port to the host, like this:
![image](https://user-images.githubusercontent.com/42527535/136868348-321efb8f-f04a-4255-8f87-6cc204c5812d.png)
but when I use [AnotherRedisDesktopManager](https://github.com/qishibo/AnotherRedisDesktopManager) or aioredis test case to connect redis sentinel, It's  doesn't  work,  but  when I run the test case on my redis deployment machine, it's worked. why?

**Comment by a-yangyi** [comment]
> At least in my case, I can confirm passing in the master IP and sentinel port when attempting to use aioredis v2, as I'm using the aioredis v2 recipes example as-is. Oddly, v1.3.1 works fine. Here's my output from the cli when connecting to the sentinel port:
> 
> ```shell
> me@localhost:~$ redis-cli -h localhost -p 26379 SENTINEL MASTERS
> 1)  1) "name"
>     2) "mymaster"
>     3) "ip"
>     4) "127.0.0.1"
>     5) "port"
>     6) "6379"
>     7) "runid"
>     8) "03f193c5821b7077191f9fa7f8bceb7289395fb4"
>     9) "flags"
>    10) "master"
>    11) "link-pending-commands"
>    12) "0"
>    13) "link-refcount"
>    14) "1"
>    15) "last-ping-sent"
>    16) "0"
>    17) "last-ok-ping-reply"
>    18) "267"
>    19) "last-ping-reply"
>    20) "267"
>    21) "down-after-milliseconds"
>    22) "30000"
>    23) "info-refresh"
>    24) "2000"
>    25) "role-reported"
>    26) "master"
>    27) "role-reported-time"
>    28) "369212266"
>    29) "config-epoch"
>    30) "0"
>    31) "num-slaves"
>    32) "0"
>    33) "num-other-sentinels"
>    34) "0"
>    35) "quorum"
>    36) "2"
>    37) "failover-timeout"
>    38) "180000"
>    39) "parallel-syncs"
>    40) "1"
> ```
> 
> Here's the recipe code and traceback, using the latest commit on master [73ae8fb](https://github.com/aio-libs/aioredis-py/commit/73ae8fbc658a19d616fb7ff5dd22076d3281be26) (v2 tagged release produces the same exception):
> 
> ```python
> Python 3.8.8 (default, Feb 24 2021, 03:57:16)
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import asyncio
>    ...:
>    ...: import aioredis.sentinel
>    ...:
>    ...:
>    ...: async def main():
>    ...:     sentinel_client = aioredis.sentinel.Sentinel([("localhost", 26379)])
>    ...:
>    ...:     master_redis: aioredis.Redis = sentinel_client.master_for("mymaster")
>    ...:     info = await master_redis.sentinel_master("mymaster")
>    ...:     print("Master role:", info)
>    ...:
>    ...:
>    ...: if __name__ == "__main__":
>    ...:     asyncio.run(main())
>    ...:
> ---------------------------------------------------------------------------
> ResponseError                             Traceback (most recent call last)
> <ipython-input-1-42ccdc545fd2> in <module>
>      13
>      14 if __name__ == "__main__":
> ---> 15     asyncio.run(main())
> 
> ~/.local/lib/python3.8/asyncio/runners.py in run(main, debug)
>      42         if debug is not None:
>      43             loop.set_debug(debug)
> ---> 44         return loop.run_until_complete(main)
>      45     finally:
>      46         try:
> 
> ~/.local/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
>     614             raise RuntimeError('Event loop stopped before Future completed.')
>     615
> --> 616         return future.result()
>     617
>     618     def stop(self):
> 
> <ipython-input-1-42ccdc545fd2> in main()
>       8
>       9     master_redis: aioredis.Redis = sentinel_client.master_for("mymaster")
> ---> 10     info = await master_redis.sentinel_master("mymaster")
>      11     print("Master role:", info)
>      12
> 
> ~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/client.py in execute_command(self, *args, **options)
>    1064         try:
>    1065             await conn.send_command(*args)
> -> 1066             return await self.parse_response(conn, command_name, **options)
>    1067         except (ConnectionError, TimeoutError) as e:
>    1068             await conn.disconnect()
> 
> ~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/client.py in parse_response(self, connection, command_name, **options)
>    1080         """Parses a response from the Redis server"""
>    1081         try:
> -> 1082             response = await connection.read_response()
>    1083         except ResponseError:
>    1084             if EMPTY_RESPONSE in options:
> 
> ~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/sentinel.py in read_response(self)
>      63     async def read_response(self):
>      64         try:
> ---> 65             return await super().read_response()
>      66         except ReadOnlyError:
>      67             if self.connection_pool.is_master:
> 
> ~/.local/lib/python3.8/site-packages/aioredis-2.0.0-py3.8.egg/aioredis/connection.py in read_response(self)
>     869
>     870         if isinstance(response, ResponseError):
> --> 871             raise response from None
>     872         return response
>     873
> 
> ResponseError: unknown command `SENTINEL`, with args beginning with: `MASTER`, `mymaster`,
> ```

halo you solved it? everyting in redis-cli is normal, but cant work in code
