### ISSUE TITLE
Implement a prefix or namespace support

### ISSUE THREAD

**Issue by cookkkie** [aio-libs/aioredis-py#120]
Hi,

It would be cool to have a `namespace` or `prefix` system.
Basically:

``` python
>> redis = yield from aioredis.create_redis(('localhost', 6379), namespace="foo:")
>> yield from redis.set('my-key', 'value')
```

would be equivalent to `SET foo:my-key value`.

What do you guys think about that?

**Comment by popravich** [comment]
Hi,
This can be nice feature however it requires some changes in library design.
I'll keep it in mind.
