### ISSUE TITLE
PUBSUB will loss messages when run a lot of time such as one day on 1.3.1

### ISSUE THREAD

**Issue by AlstonMa** [aio-libs/aioredis-py#1200]
### Describe the bug

When I use PUBSUB , It will loss messages when run a lot of time such as one day.
the subscriber will received 50 mesaage every 5S . I see the log . sometimes will lose one .
By the way , the redis connection is still alive.
How can I fixed it.

### To Reproduce

async def reader(self, mpsc):
        try:
            async for channel, msg in mpsc.iter():
                channel = channel.name.decode("utf-8")
                msg = msg.decode("utf-8")
                if channel == 'strategyDataComplete':
                      print("do something")

### Expected behavior

I need to fixed it . I do not want to loss message.

### Logs/tracebacks

```python-traceback
nothing
```

### Python Version

```console
$ python --version
3.8.10
```

### aioredis Version

```console
$ python -m pip show aioredis
1.3.1
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Andrew-Chen-Wang** [comment]
We do not support 1.3.1 anymore; please upgrade. Though, I can't really explain why it would drop messages. Can you override the `__iter__` of the PubSub class to see your actually receiving bytes? If you're not receiving anything, it's not an aioredis issue or it could be a socket/buffer issue in aioredis or Redis itself is somehow failing.

**Comment by AlstonMa** [comment]
thanks for reply. I have upgrade . and I used asyncio loop for more redid client . It resolve the problem . I thinks the bug is caused by Redis'buffer.

--------------原始邮件--------------
发件人："Andrew Chen Wang ***@***.***&gt;;
发送时间：2021年11月21日(星期天) 凌晨0:24
收件人："aio-libs/aioredis-py" ***@***.***&gt;;
抄送："AlstonMa ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [aio-libs/aioredis-py] PUBSUB will loss messages when run a lot of time such as one day (Issue #1200)
-----------------------------------

 

 
We do not support 1.3.1 anymore; please upgrade. Though, I can't really explain why it would drop messages. Can you override the __iter__ of the PubSub class to see your actually receiving bytes? If you're not receiving anything, it's not an aioredis issue or it could be a socket/buffer issue in aioredis or Redis itself is somehow failing.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
