### ISSUE TITLE
Frequent connection errors

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aioredis-py#1281]
We are now getting frequent connection errors in the CI for aiohttp-session for 2.0.1. Doesn't seem to be a problem with 2.0.0.

Any ideas on what is happening there would be great:
https://github.com/aio-libs/aiohttp-session/pull/652

**Comment by Andrew-Chen-Wang** [comment]
nothing conn wise should have changed. Unfortunately, I'm a little busy with midterms and migrating aioredis to Redis-py with RedisLabs. I will come back to this once things have settled over there. Sorry!

**Comment by seandstewart** [comment]
Seems like there were a few changes around reading and parsing responses, no idea if that could be the issue, but it's a place to start.

https://github.com/aio-libs/aioredis-py/compare/v2.0.0...v2.0.1

**Comment by Dreamsorcerer** [comment]
Thanks, I've found it: https://github.com/aio-libs/aioredis-py/compare/v2.0.0...v2.0.1#diff-6d3e65633ef76c2cc5e938736e2b2190317629f27f99f24384f4f1def6bd151dR10

Not sure if you want to consider reverting that change or not, but the conftest has some retry logic after catching `ConnectionError`. I've fixed it by referring to the redis one. I'd consider renaming it though, to avoid clashing with the builtin (`RedisConnectionError` or something).

**Comment by seandstewart** [comment]
Great - thanks for isolating the issue.

This is one of those chicken-egg scenarios where this exception is actually mimicking redis-py's (questionable) implementation.

An additional option would be to have our connection error inherent from the builtin, which feels sensible to me.

**Comment by Dreamsorcerer** [comment]
That's what it did, the changelog shows the inheritance was removed. Appears to be this PR: https://github.com/aio-libs/aioredis-py/pull/1129

I'll leave you to decide if that change should be reverted or not.
