### ISSUE TITLE
Sentinel peers discover

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis-py#185]
Implement sentinel peers discovery

**Comment by dpereira** [comment]
Hello, @popravich, we're very interested in using aioredis with sentinel support. It seems this is the last task related to it in the 1.0 milestone. 

I'd like to understand if the code is already functional, or if there are any other pending issues for sentinel support.

Regards.

**Comment by popravich** [comment]
Hi, @dpereira,
Sentinel support is available in master, it is functional.
However few things are missing: dynamic peers discovery; more docs & more tests.
Some docs are here — http://aioredis.readthedocs.io/en/latest/sentinel.html

**Comment by runtel** [comment]
Hi all.
Tell me please, when new server discovered, the channels resubscribe?
Or it's posible to make callback when server discover?

Thanks!

**Comment by popravich** [comment]
Hi, @runtel 
Peers discovery is not yet implemented, so the answer to your first question is no.
In general, Pub/Sub channels do not resubscribe on disconnects, the reason behind this is that
some messages may be published to channels before reconnected client will resubscribe and
so those messages will be lost. So having aioredis silently resubscribing on disconnects is inconvenient.

As for callback when server discovered — this is a good idea and should be implemented as part
of this feature.

**Comment by runtel** [comment]
One of the way is check count channel after new master discover and check is active a mpsc like this:

```python
while True:
    if not mpsc.is_active or redis.in_pubsub == 0:
        await resubscribe_cannels_func()
    await asyncio.sleep(1)
```
