### ISSUE TITLE
update `set(.., exist=)` command to accept `nx`/`xx` parameter values

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis-py#194]
Currently it accepts two constants `Redis.SET_IF_NOT_EXIST` (stands for `NX`) and `SET_IF_EXIST` (`XX`).
I think this is a bit confusing.

TODO:
* [ ] allow `await redis.set(..., exist='nx')  # case-insensitive`
* [x] keep current constants: `await redis.set(..., exist=redis.SET_IF_EXIST)`
* [ ] update docs adding parameters description

**Comment by argaen** [comment]
IMO a clearer way to do this would be reusing the `setnx` and `setex` commands. They are missing the TTL but internally they could endup both using the normal `set` command passing the options you said above.

**Comment by popravich** [comment]
Well, this can bring inconsistency to someone using old Redis server (which does not support extended `set` format).

**Comment by argaen** [comment]
Ahhh I see. Anyway from what I read in https://github.com/andymccurdy/redis-py/issues/387 this has been around for almost 4 years now..
