### ISSUE TITLE
Problems with "Getting Started" docs

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis-py#349]
I'm afraid it looks like no one has though about the docs at a high level for a long time.

http://aioredis.readthedocs.io/en/v1.0.0/start.html:

* goes straight into examples of pipelining without a basic example of simple usage
* There's a "Python 3.5 async with / async for support" section even though I think 3.4 has been dropped so this section doesn't make sense.
* The second pub/sub example is incomplete, it doesn't show where the pool was created even though at that point in the docs there's been nothing about pools whatsoever.
* There's no clarity in getting started on pools vs. connections, how they're used
* "SSL/TLS support" has nothing to do with getting started

In the readme:
* connections are described before pools even though most people should be using pools
* the low level interface is described before the high level interface even though <1% of people will want to use the low level interface

Sorry to criticise but aioredis used to have good docs (written by @asvetlov I think?) and now it doesn't. This is a step backwards.

**Comment by asvetlov** [comment]
No, aioredis documentation is written by @popravich 
I hope Alexey will find a time for improving it.
