### ISSUE TITLE
Redis password shown in logs in plain text

### ISSUE THREAD

**Issue by lilydjwg** [aio-libs/aioredis-py#399]
In `create_connection` the URL is logged without masking the password, so it will be in the debug log. I didn't expect this and I see other libraries masking passwords with stars in logs.

Wouldn't it be better for aioredis to mask it out so people who are debugging their code won't accidentally let out the password unknowingly.

**Comment by popravich** [comment]
PR is welcome.

**Comment by marcstreeter** [comment]
happens [here](https://github.com/aio-libs/aioredis/blob/master/aioredis/connection.py#L78) -- in case anyone wants to hit it. The fix seems easy enough. I'll take a look sometime this weekend.

**Comment by popravich** [comment]
The fix can be as simple as just moving that log 1 line down and rephrasing to "Parsed Redis address %r"
