### ISSUE TITLE
Can we execute a command which is not available in any of the Mixins?

### ISSUE THREAD

**Issue by SrujithPoondla** [aio-libs/aioredis-py#407]
For example, I am using Redis-ML module and it contains few new commands for matrices. redis_py has a function 'execute_command' to execute any command even if it doesn't have a client-side implementation. I am wondering whether is there a similar function available in aioredis?

**Comment by popravich** [comment]
Yes, there is a method [RedisConnection.execute](http://aioredis.readthedocs.io/en/v1.1.0/api_reference.html#aioredis.RedisConnection.execute), it is exposed on both `ConnectionsPool` and `Redis` mixins interface.

**Comment by lemurchik** [comment]
I will(probably during the next week). I already have a branch where all ci tests are passed. But any way it will be part of this pull request https://github.com/aio-libs/aioredis/pull/119

**Comment by SrujithPoondla** [comment]
@lemurchik  I would say you can create a new pull request directly to aioredis instead of merging with yamp and then yamp to panda and panda to #199. I compared your master and aioredis master, there are no conflicts and able to merge. I am not sure whatever I am saying is the correct way or not.

**Comment by karanlyons** [comment]
I may be wrong, but it appears you can’t execute commands not available in the mixins as part of a pipeline due to `Pipeline.execute` “shadowing” `Redis.execute`. Is there a proper way to execute undefined commands in _all_ the normal interfaces (client, pool, connection, pipeline, transaction, etc.)?

**Comment by SrujithPoondla** [comment]
@lemurchik  Could you please raise a pull request and merge the cluster support?
