### ISSUE TITLE
subscribe 1000 channels simultaneously

### ISSUE THREAD

**Issue by ljcljc** [aio-libs/aioredis-py#417]
Hi, I am not trying to subscribe 1000 channels, which sends message every 0.1 second. I modified the examples from pub/sub. The strange thing is that I found data got lost sometimes.

All this is in one process, one thread, is there a upper limit on how many channels to subscribe? I don't want any data to get lost here. Thanks

**Comment by popravich** [comment]
It is hard to say what is wrong. Please provide code example recreating the problem.

**Comment by ljcljc** [comment]
This is the code I use from pub/sub sample.

`import asyncio
import aioredis


async def reader(ch):
    while (await ch.wait_message()):
        msg = await ch.get_json()
        print(ch.name, "Got Message:", msg)


async def main():
    sub = await aioredis.create_redis(
        'redis://localhost')
    stock_list= ['2','666']#one thousand channel list
    for stock in stock_list:
        res = await sub.subscribe(stock)
        ch1 = res[0]

        tsk = asyncio.ensure_future(reader(ch1))
    await tsk


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())`
