### ISSUE TITLE
Pubsub: Subscribe never unsubscribes

### ISSUE THREAD

**Issue by arjunpat** [aio-libs/aioredis-py#423]
Hello,

I am working on a pub/sub server that uses the following code:
```
# subscribes to the desired channel
ch = (await redis_conn.subscribe(channel))[0]

# awaits a message from redis
while await ch.wait_message():
	msg = await ch.get_json()
	await resp.send(msg['message'], id = msg['eid'])

# unsubscribes from redis pub/sub
await redis_conn.unsubscribe(channel)
print('unsubscribed')
```

Although it makes sense for the code to never reach the `await redis_conn.unsubscribe(channel)`, I still need a way to unsubscribe and delete the channel so I don't encounter memory leaks or slow downs when hundreds of people are using this at the same time over multiple days.

Does anybody have any ideas of how to refactor this code so that the unsubscribe function will always be reached OR the channel will be deleted at some point if no subscribers exist?

Note: when the user leaves the page, the unsubscribe function is not reached (from a logical perspective, this makes sense).

**Comment by popravich** [comment]
What is `resp.send(....)`?
Looking at this code I imagine two ways how execution could reach `unsubscribe`:
* either a special marker message should be posted to channel to break the `while` loop;
* or `resp.send` call should return some condition to break the loop (or raise exception);

**Comment by blueyed** [comment]
I think the problem might be that `CancelledError` gets raised.

Try using a `try` block and `unsubscribe` in the `finally`?
Something along:
```python
async def get_channel(redis_addr, topic):
    conn = await aioredis.create_connection(redis_addr)

    await conn.execute_pubsub('psubscribe', topic)
    channel = conn.pubsub_patterns[topic]

    try:
        return channel
    finally:
        # TODO: check if active/open still before?!
        await conn.execute_pubsub('punsubscribe', topic)
        conn.close()
```
