### ISSUE TITLE
PoolClosedError, ConnectionForcedCloseError

### ISSUE THREAD

**Issue by kabell** [aio-libs/aioredis-py#428]
Hi,
I'm developing heavily used api (100k requests/ hour) using aiohttp which uses aoiredis for connecting to redis.
The app has created redis pool of connections

`conn_pool = await aioredis.create_pool(address='some_address', min_conn=2, max_conn=500, encoding='utf-8')`

and in each request I call

`result = await conn_pool.execute('mget', *not_cached_keys)`

It works pretty well up to some requests (~100/ hour) are failed with exception PoolClosedError or ConnectionForcedCloseError.

The pool is definitely not closed. Except shutdown of the server I never call close method on that pool. Also the next requests are not issued with this.

Can you please help me solve that ?

**Comment by popravich** [comment]
It is hard to say what is wrong without examining your code.

**Comment by stypr** [comment]
I have very similar issue, there should be some tests based on this bug. 
My service also does 10k req/min and somehow mget makes PoolClosedError after a bit of time..

**Comment by kabell** [comment]
Hi, sorry I didn't let you know, for me the issue is solved.
I used gunicorn as a http server and it always restarts a worker after 5K requests (to prevent memory leaks etc.) However I used `on_shutdown` signal to stop the worker. When I replaced it to `on_cleanup` it works without problem.
