### ISSUE TITLE
Locks in redis

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aioredis-py#43]
Would be nice to have.

**Comment by mackeyja92** [comment]
Any status on this?

**Comment by joanvila** [comment]
In order to have locks, I've been working on a library that implements the redlock algorithm:
https://github.com/joanvila/aioredlock
There are things to improve there but I've been using it.

**Comment by popravich** [comment]
Sorry, no progress on this.
You can try suggested library or submit a PR

**Comment by lirsacc** [comment]
For simple locks, we have implemented  [`Lock`](https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py) from `redis-py` on top of `aioredis`.  Not as powerful as redlock but if there is interest in having this in the library, I could try and make a PR.

**Comment by jekel** [comment]
@lirsacc can you make a PR or share it in your repo please?

**Comment by mrasband** [comment]
Sorry for the noise getting a PR up, but I ported over the redis-py implementation. It's pretty nice and short in asyncio!

Thanks for the library :)

**Comment by mrasband** [comment]
I pulled out the code from my PR #573 into a standalone thing for anyone that may need this, hopefully I can archive it if/when we have support in aioredis: https://pypi.org/project/aioredis-lock/
