### ISSUE TITLE
redis stream support

### ISSUE THREAD

**Issue by bsergean** [aio-libs/aioredis-py#438]
Hi there, here are a bunch of questions around redis streams.

1. What is the plan for supporting redis stream? Wait until the feature is out of beta and redis 5 is released? 
2. Should it be implemented like pubsub, or more like a normal set of commands. 
3. Also I guess that it has to be supported in hiredis first ?
4. Would it be possible to try to implement it outside of redis stream in my own project, using monkey patching or something similar, until the support is really here (as is, how extensible aioredis is). That could be a bad idea?

Thanks for any thoughts !

**Comment by barrachri** [comment]
https://github.com/aio-libs/aioredis/pull/299 is already inside master.

**Comment by adamcharnock** [comment]
Hey @barrachri, I think this would be a good feature. I don't have time to look into it right now, but I'd be happy to look over any pull request if you wish (although I have no authority to merge).

**Comment by barrachri** [comment]
Ok, thanks @adamcharnock!

**Comment by barrachri** [comment]
https://github.com/aio-libs/aioredis/pull/472

**Comment by vostok4** [comment]
Some commands are still missing (XDEL) and (XTRIM), is it possible to get them in as well?

**Comment by ivarec** [comment]
Is this the main issue to track the development of XDEL and friends?

**Comment by curiouscod3** [comment]
Please Support XDEL and  XTRIM !

**Comment by curiouscod3** [comment]
I've added xdel and xtrim. Still needs some test in real world. Please try it
