### ISSUE TITLE
How to detect disconnection with pubsub

### ISSUE THREAD

**Issue by Gerporgl** [aio-libs/aioredis-py#468]
Is there a proper method to detect disconnections when connected to a remote redis server and using the subscribe method?

In case the redis server is remote it is important that if the communication is cut and even may be closed by in-between firewalls that it is detected using some kind of read/write timeout.

I've tested this with several other async redis library for python and I haven't been able to setup a reliable method to rapidly detect those disconnections. In all cases the connection appear to be still connected indefinitely even though no pubsub messages published on the redis server are coming anymore from the channel.wait_message()

**Comment by popravich** [comment]
You can check Channel's `is_active` attribute — it will be `False` if channel is closed (either from server or client side) (see the test from PR)

**Comment by arebrik** [comment]
> You can check Channel's `is_active` attribute — it will be `False` if channel is closed (either from server or client side) (see the test from PR)

Hello! `ch.iter()` in your test actually block until message received and it will never happened if connection close. As solution, we can use other task where `is_active` checks will call periodically, but it doesn't seems good solution.

As I understand, `ch.get()` will waits for message and raise `ChannelClosedError` on connection close, so we can write something like this
```
while 1:
  try:
    msg = await ch.get()
  except ChannelClosedError:
    #on connection close operations
```

But I don't understand, why than we need to use  `ch.iter()` or `ch.wait_message()`?
