### ISSUE TITLE
Redis RuntimeError while using Pytest

### ISSUE THREAD

**Issue by stopfaner** [aio-libs/aioredis-py#495]
When I use Redis client based on aioredis and test this code with pytest, I usually get an error:

`RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x7fb9f7d83a28>; the handler is closed`

I create my connection object via `create_redis_pool()` and check before every request if connection is open with `connection.closed`, which returns me `False` every time, but after that I get a RuntimeError, which shows, that connection is closed.

Meanwhile, this Redis client works fine in code, error occurs only in tests.

**Comment by popravich** [comment]
Hi, @stopfaner , can you provide minal example code to recreate the issue?
The problem may be in many places its just not enough information.

**Comment by NovemberOscar** [comment]
Hi, I have the same problem. 

I'm using pytest with pytest-sanic, pytest-redis.

here's my sanic test cli fixture.

```python
@pytest.yield_fixture(scope="function")
async def hermes_app(mysql_proc, mysql, redis_proc):
    _app = create_app()

    _app.database_connection_info = {
        "use_unicode": True,
        "charset": "utf8mb4",
        "user": mysql_proc.user,
        "db": "pytest_mysql_db",
        "host": mysql_proc.host,
        "port": mysql_proc.port,
        "autocommit": True,
    }

    _app.cache_connection_info = {
        "address": f"redis://:@{redis_proc.host}:{redis_proc.port}",
    }

    yield _app


@pytest.fixture(scope="function")
def test_cli(loop, hermes_app, sanic_client):
    return loop.run_until_complete(sanic_client(hermes_app))
```

and here is my test code.

```python
@pytest.mark.parametrize(
    "method,endpoint,request_body,expected_response_status,expected_response_body",
    admin_view_test_data(),
)
async def test_admin_view(
    test_cli,
    method,
    endpoint,
    request_body,
    expected_response_status,
    expected_response_body,
):
    r = await getattr(test_cli, method.lower())(uri=endpoint, data=json.dumps(request_body))
    assert r.status == expected_response_status
```

and it gives such error. but it appears randomly...

```
```

**Comment by NovemberOscar** [comment]
I solved this issue with a release connection when teardown. 
make sure you release the connection when teardown. :)
