### ISSUE TITLE
Blocking operations interfere with acquiring a pool connection

### ISSUE THREAD

**Issue by bbridges** [aio-libs/aioredis-py#511]
I'm currently having a problem where if a blocking operation is running in the background, and I'm needing to acquire a connection to use with `watch`/`unwatch` several times, eventually the connection waits until the blocking operation is done to use that connection instead of the other free connections. If it takes a while for the blocking operation to go through it prevents my transaction from happening.

Here's a minimal example that will cause this to happen:

```python
import asyncio

import aioredis


loop = asyncio.get_event_loop()


async def main():
    redis = await aioredis.create_redis_pool('redis://localhost', minsize=5,
                                                                  maxsize=10,
                                                                  loop=loop)

    # Run a background operation.
    redis.brpop('something')

    for i in range(0, 20):
        print(i)
        # Acquiring a connection and doing something.
        with await redis as r:
            await r.set('test', 1)

    redis.close()
    await redis.wait_closed()


loop.run_until_complete(main())
```

For me, the above runs the loop twice, waits until the blocking operation finishes, and then continues. Making the blocking task acquire its own connection manually will fix the problem, but it won't work without doing that in the above.

Edit: Similar behavior happens when not acquiring it manually, i.e. just running `redis.set('test', 1)` directly, but the loop runs 5 times instead before stopping.

**Comment by adrianog** [comment]
The example you reported is similar to what I see in the documentation (https://goo.gl/7d9QZS), except:
1) The redis variable is used outside of the async coroutine (shouldn't matter)
2) There is no brpop example in that documentation (unfortunate as that is a clear blocking case).

In your case the "exclusive" mode should be applied to the brpop call, so:
```
# Exclusive mode
with await redis as r:
  await redis.brpop('something')

 for i in range(0, 20):
        print(i)
        # Shared mode
        await redis.set('test', 1)
```

**Comment by bbridges** [comment]
Yeah I have to use

**Comment by adrianog** [comment]
I'd call it a known limitation with an effective workaround.

PS: I think a lot of people come to aioredis with that blocking use case in mind, and I wish more prominence was given to this issue - why isn't brpop in the docs given that that is a glaring blocking example .

**Comment by pbecotte** [comment]
Thanks, just came here to ask what I was doing wrong, but this solves what I needed.
