### ISSUE TITLE
Transactional execution can mishandle asyncio task cancellation

### ISSUE THREAD

**Issue by himikof** [aio-libs/aioredis-py#530]
I have seen the following exception to occur when executing a MultiExec transaction:
```
Traceback (most recent call last):
  <snipped>
  File "venv/lib64/python3.7/site-packages/aioredis/commands/transaction.py", line 176, in execute
    conn, return_exceptions=return_exceptions)
  File "venv/lib64/python3.7/site-packages/aioredis/commands/transaction.py", line 299, in _do_execute
    return (await self._gather_result(return_exceptions))
  File "venv/lib64/python3.7/site-packages/aioredis/commands/transaction.py", line 201, in _gather_result
    raise self.error_class(errors)
aioredis.errors.MultiExecError: ('MultiExecError errors:', [CancelledError()])
```
The `asyncio.CancelledError` inside of the `MultiExecError` has this traceback:
```
Traceback (most recent call last):
  File "venv/lib64/python3.7/site-packages/aioredis/commands/transaction.py", line 195, in _gather_result
    res = await fut
concurrent.futures._base.CancelledError
```

The error happens very rarely in a complicated test suite, and seems to be very timing-dependent. So I'm afraid I won't be able to provide a reproducer. The test in question is cancelling the task running the Redis transaction while it is executing.

As I understand it, the issue is in `Pipeline._gather_result` code:
```python
    async def _gather_result(self, return_exceptions):
        errors = []
        results = []
        for fut in self._results:
            try:
                res = await fut
                results.append(res)
            except Exception as exc:
                errors.append(exc)
                results.append(exc)
        if errors and not return_exceptions:
            raise self.error_class(errors)
        return results
```
In asyncio any await expression can raise `asyncio.CancelledError` on task cancellation. Unfortunately, `asyncio.CancelledError` is derived from `Exception`, not `BaseException`, so this code captures it and stores in the `errors` list. And then a `PipelineError`/`MultiExecError` is raised, replacing the task cancellation with an unexpected exception (worst case, the calling code logs the unexpected error and continues, and task cancellation is now lost).

I suppose it should be the same issue as #477.
The aioredis version is 1.2.0.

**Comment by absolutelyNoWarranty** [comment]
Reproducing #477  with `pipeline`
```
import asyncio
import aioredis


async def go(redis):
    pipe = redis.pipeline()
    pipe.set('my-key2', 'value')
    await pipe.execute()


async def main():
    redis = await aioredis.create_redis_pool(
        'redis://localhost')
    task = asyncio.ensure_future(go(redis))

    await asyncio.sleep(0)
    task.cancel()

    try:
        await task
    except asyncio.CancelledError:
        pass

    val = await redis.get('my-key1')
    print(val)
    redis.close()
    await redis.wait_closed()


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Output:
```
aioredis.errors.PipelineError: ('PipelineError errors:', [CancelledError()])
```

However, replacing `pipeline` with `multi_exec` does not result in the same error.
