### ISSUE TITLE
Why keyword arguments for SortedSet commands  should be bytes

### ISSUE THREAD

**Issue by gyermolenko** [aio-libs/aioredis-py#596]
Argument type for many SortedSet commands (for `min`/`max` kw) is enforced by isinstance check.
In one place it even has this comment:
```python
if not isinstance(max, bytes):  # FIXME     Why only bytes?
    raise TypeError("max argument must be bytes")
```

I think it is more convenient (for me as a user) to pass strings inst. of bytes.
Some of these commands are for "lexicographical" operations (so user mostly works with strings and not blobs of bytes)

Also strings would be more consistent with other commands.

Should I work on a PR for the change?
If there is a deep reason for that - could you please explain the logic behind it? 
Thanks.

**Comment by popravich** [comment]
Yes, this is inconvenient, please provide a PR

**Comment by undali** [comment]
I am working on this. I've a question.

Do we need to provide backwards compatibility (by accepting byte parameters too)?
