### ISSUE TITLE
when aioredis support redis cluster?

### ISSUE THREAD

**Issue by wingzzzz** [aio-libs/aioredis-py#597]
When aioredis support redis cluster, please? The status is WIP, and have been WIP for a very long time.

**Comment by bsergean** [comment]
There's a redis proxy coming up that might make this less of an issue.

Salvatore talks about it a bit here -> https://www.youtube.com/watch?v=lo-Pgf_l7_M

**Comment by yurymann** [comment]
@bsergean , is there an update on this, please? We have chosen aioredis as the strategic asyncio redis client, assuming redis cluster is naturally supported. Is it completely not supported, or just certain features? Where can we read more about this?

Thanks

**Comment by bsergean** [comment]
I don't think that cluster support is on the roadmap. I cannot speak for this project.

**Comment by DriverX** [comment]
Redis Cluster support for aioredis
https://pypi.org/project/aioredis-cluster/

**Comment by yurymann** [comment]
@DriverX interesting, thanks, I'll take a look.

**Comment by DachuanZhao** [comment]
Any processing ?

**Comment by Andrew-Chen-Wang** [comment]
When PR #891 is merged, it should be enabled since it's a redis-py port... but don't quote me on that.

**Comment by wingzzzz** [comment]
> Redis Cluster support for aioredis
> https://pypi.org/project/aioredis-cluster/

Thank you!

**Comment by wingzzzz** [comment]
> Redis Cluster support for aioredis
> https://pypi.org/project/aioredis-cluster/

Thank you!

**Comment by utkarshgupta137** [comment]
redis-py doesn't support cluster mode: https://github.com/andymccurdy/redis-py/issues/1385. I don't think basing code around it will work. For cluster support, I think a separate implementation will be required based on https://github.com/Grokzen/redis-py-cluster

**Comment by HanfordWu** [comment]
Hey team, I see doc saying v2.0 doesn't support cluster, but to what degree it support cluster mode? Though I don't find a way to connect to a cluster.

**Comment by Andrew-Chen-Wang** [comment]
It technically can and there is already #1256 that implements it

**Comment by HanfordWu** [comment]
That's great to know, cannot wait to see it released.
