### ISSUE TITLE
Is it possible discard queued commands in transaction?

### ISSUE THREAD

**Issue by yakkle** [aio-libs/aioredis-py#624]
When using [transaction](https://redis.io/topics/transactions) how to discard queued commands?

```py
>>> redis = await aioredis.create_redis_pool('redis://localhost')
>>> tr = redis.multi_exec()
>>> tr.set('k1', 'v1')
>>> await tr.execute()
```
This is sample code in documents but `MultiExec(Pipeline)` class has no discard function.
I don't know how to discard transaction before execute.

aioredis is not support redis transaction discard?

**Comment by popravich** [comment]
Oh, I'm afraid this is still not implemented.
