### ISSUE TITLE
Are pools useful in simple cases ?

### ISSUE THREAD

**Issue by octopoulpe** [aio-libs/aioredis-py#635]
Hi !
Pools usefulness is not explicit in the documentation. So I looked at the code and I'm still not sure if it's a good idea to create a connection pool if you don't use blocking calls, pubsub, and pipelining (as the connections are nonblocking).

My question(s) :
Is it useful to create a pool if you only need to use get/set ?
If yes, how may I estimate when it's a good idea to do so, depending on the volume and concurrency model of my application ?

Great project anyhow !

**Comment by popravich** [comment]
Hi, @octopoulpe 

> If yes, how may I estimate when it's a good idea to do so, depending on the volume and concurrency model of my application ?

It all depends.
My recommendation is to use pool as it handles reconnections. Bare connection objects may be more useful if you need to implement your own pool logic.

On the other hand if your application only do several get/set operations in long intervals it may be
better to use connections — open new one, perform operations, close it and forget.
