### ISSUE TITLE
Add ability to ignore ssl cert for verification purposes

### ISSUE THREAD

**Issue by whoshuu** [aio-libs/aioredis-py#637]
I am using both this library and the redis-py library to interface with an Elasticache cluster. When using encryption in transit for Elasticache, there is an issue where the cert being propagated is not valid, though the messages are encrypted nonetheless. The redis-py library has an option `ssl_cert_reqs` that can be used to skip verification of that cert. Currently I can't use aioredis for the same cluster, and having an option like this would allow me to use it.

**Comment by popravich** [comment]
Hi,
See `ssl` parameter description and `ssl.SSLContext` API docs — https://aioredis.readthedocs.io/en/v1.2.0/api_reference.html#aioredis.create_redis
Basically, you need to supply preconfigured `SSLContext` instance.

**Comment by samuraisam** [comment]
Here is what I am doing with `django-channels` and `channels-redis` - it allows you to add a flag to the host string `?ssl_cert_reqs=false` to disable host verification:

```python
import ssl
from urllib.parse import urlparse, parse_qs
from channels_redis.core import RedisChannelLayer
from channels_redis.core import ConnectionPool


class SslNoVerifyConnectionPool(ConnectionPool):
    def __init__(self, host):
        address = urlparse(host['address'])
        if address.query:
            query = parse_qs(address.query)
            if 'ssl_cert_reqs' in query and 'false' in query['ssl_cert_reqs']:
                print('disable ssl cert reqs')
                host['ssl'] = ssl._create_unverified_context()
        super().__init__(host)


class CustomRedisChannelLayer(RedisChannelLayer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.pools = [SslNoVerifyConnectionPool(host) for host in self.hosts]
```
