### ISSUE TITLE
Implement new Cluster commands

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis-py#64]
Redis 3.0 introduced new Cluster commands.
Need to implement them.
see http://redis.io/commands#cluster

**Comment by misja** [comment]
I'll be needing cluster support soon - don't dare ask, but is there some ETA soon ... ? Else, would like to see if I can contribute, are there any thoughts yet on implementation details?

**Comment by popravich** [comment]
Hi, @misja,
I'm in progress with new commands.
Implementing them should not take long but the most complicated part is the tests.
Anyway, I've created [branch](https://github.com/aio-libs/aioredis/tree/commands_3.0) where the work is being done and PRs are welcome.

**Comment by misja** [comment]
Oh excellent, I'll be closely following developments!

**Comment by nasenbaer13** [comment]
There is a [fork](https://github.com/trezorg/aioredis/commit/794f023a7f9bc6e0005516c1f2fb1232a6ad05f4) implementing  an abstraction for redis cluster. We would love to see this in aioredis. @popravich do you consider merging the fork from @trezorg? If so - we could help out with writing some tests for the redis cluster abstraction.

**Comment by popravich** [comment]
Oh, didn't see it, I will take a look

**Comment by the-panda** [comment]
I have created a [pull request](https://github.com/aio-libs/aioredis/pull/119) to add cluster support. The [fork](https://github.com/ymap/aioredis) is based on @trezorg's fork mentioned above.

**Comment by kxepal** [comment]
@popravich @the-panda 
Hey! What's the status of this issue? It's quite old and has PR with the code, but is there any else work need to be done? Do you need any help with?

**Comment by myrfy001** [comment]
How is it going?
I think the cluster feature should be added ASAP.

**Comment by the-panda** [comment]
I'm working on merging the master branch into my PR branch. Currently, I have merged ~130 of 230 commits, including the switch to PyTest, so I guess most of the work is done. However, since the PR branch works quite well at my organization, I'm afraid that this merge has not the highest priority right now.

**Comment by vineet-rh** [comment]
Is there any updated ETA when we can start using `aioredis` for clustering

**Comment by kstrempel** [comment]
Would be nice to get an update about that topic..

**Comment by DriverX** [comment]
Redis Cluster support extension library for aioredis
https://pypi.org/project/aioredis-cluster/
