### ISSUE TITLE
Pub/Sub is blocking?

### ISSUE THREAD

**Issue by thebpmgroup** [aio-libs/aioredis-py#660]
I have implemented a 1 channel pub > sub as per the demo and it is working ok.

One comment is that if I add some IO intensive task in the reader function, in this case sending an email to the user that just signed up, then it seems to block the caller until the email is sent, which I thought wasn't supposed to happen?

`async def reader(ch):
    while (await ch.wait_message()):
        try:
            msg = await ch.get_json()
            sendemailandtakeagesdoingit(msg[1][1]) #msg[1][1] is the email address
        except Exception as e:
            print(str(e))`

And I publish the message to the queue like :+1: 
`pub.publish_json('user:1', ["new_user_email",
                                                                  ["uid",uid]])`

I thought it would publish to the queue and continue on but it blocks until the email is sent. Is this behaviour by design? Have I misunderstood the publisher subscriber pattern?

**Comment by popravich** [comment]
@thebpmgroup, 
Looking at your example, it seems that `sendemail...` is blocking and it is not related to aioredis.
