### ISSUE TITLE
XREAD hangs with default timeout=0

### ISSUE THREAD

**Issue by greenwolf-nsk** [aio-libs/aioredis-py#677]
Hi!

Noticed that Redis hangs sometimes on commads like `XREAD BLOCK 0 mystream 0-0`, especially if there is no such stream in the database.
And it seems to be a bug in aioredis: https://github.com/aio-libs/aioredis/blob/master/aioredis/commands/streams.py#L275, timeout is checked for `None`, but default value is 0, so we add `BLOCK 0` to command.

Steps to reproduce:

Redis ersion: 5.0.5
aioredis version: 1.3.1
python version: 3.7

```
import aioredis
import asyncio


async def xadd_xread():
    redis = await aioredis.create_redis_pool(address=('localhost', 6379))
    await redis.flushdb()
    print(await redis.xread(streams=['test_stream'], latest_ids=['0-0']))  # hangs 
    # print(await redis.xread(streams=['test_stream'], latest_ids=['0-0'], timeout=None)) # works


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(xadd_xread())
```

Suggestions: 
1) change `if timeout is None:` for `if not timeout:`
2) change default timeout to None

**Comment by larsclaussen** [comment]
I have a similar issue. I tried to reproduce your guys [test case](https://github.com/aio-libs/aioredis/blob/80abe42e833506e2feeaf09c27d29f4c6c151a1b/tests/stream_commands_test.py#L272) but it never yields an empty list like I would expect. Essentially, I run this code    

```
await client.xread(["mystreamm"], timeout=100)  # blocks forever, stream does not exist
await client.xread(["mystreamm"], timeout=0)  # blocks forever, stream does not exist
await client.xread(["mystreamm"], timeout=1)  # blocks forever, stream does not exist
await client.xread(["mystreamm"], timeout=None)  # blocks forever, stream does not exist
```
