### ISSUE TITLE
Connection <RedisConnection [db:0]> has pending commands, closing it.

### ISSUE THREAD

**Issue by TensorTom** [aio-libs/aioredis-py#695]
Using redis for session:
```
from aiohttp_session import setup as setup_session
from aiohttp_session.redis_storage import RedisStorage
from aioredis import create_pool

redis_pool = await create_pool(('localhost', 6379), password="***")
setup_session(app, RedisStorage(redis_pool, cookie_name="mysite"))
```
I'm getting the following message in my log: `Connection <RedisConnection [db:0]> has pending commands, closing it.`

What's going on here?

**Comment by VSHUMILIN97** [comment]
https://github.com/aio-libs/aioredis/blob/80abe42e833506e2feeaf09c27d29f4c6c151a1b/tests/pool_test.py#L175-L200

I wonder if this helps, but ..

**Comment by seandstewart** [comment]
This should no longer occur in the master branch, as of #891. There will be an alpha release soon with the updates to  aioredis, but in the meantime you can install from the  repository and  test if you still have any issues.
