### ISSUE TITLE
No way to execute an arbitrary command on a pipeline

### ISSUE THREAD

**Issue by yurymann** [aio-libs/aioredis-py#715]
Pipeline.exectute() shadows ConnectionsPool.execute() and RedisConnection.execute(). 
As the result, one cannot execute arbitrary commands in a pipeline. 
I use Redisearch module and need to execute multiple commands like "FT.DEL" in a row, but cannot use pipelining. 

In redis-py, the method to execute a command is called Redis.execute_command(), which ensures there is no clash. 

Happy to be told that there is a way of doing this in aioredis. 

Thanks

**Comment by gdassori** [comment]
Bump? Any way to do this ?

**Comment by yurymann** [comment]
@gdassori I worked it around by putting my pipelines into a LUA script which can be executed in a pipeline. You could probably monkey-patch it, I didn't try. 

It's pretty sad that this project, being the best maintained asyncio redis client, has been stale since December 2019.

**Comment by seandstewart** [comment]
@yurymann @gdassori 

Maintenance for this project is back on! I have limited time but am working to get tickets like these triaged and merged in. See #822. 

The next release will be a breaking change, so I'm open to someone doing as @yurymann said and renaming the Connection/ConnectionPool method to `execute_command`.

**Comment by seandstewart** [comment]
This has been resolved as of #891.
