### ISSUE TITLE
Failing to discover sentinel instances results "Task was destroyed but it is pending!"

### ISSUE THREAD

**Issue by mohammadhzp** [aio-libs/aioredis-py#742]
Currently calling `aioredis.create_sentinel()` makes a call to `create_sentinel_pool()`, 

now `create_sentinel_pool()` create a sentinel pool using SentinelPool and then call its `discover()` method.
What we need to consider is that SentinelPool class starts a coroutine in its constructor called echo_events.

At this point, when discover() didn't get to connect to any sentinel. it raises an `Exception` but `create_sentinel_pool` does not handle that error. you see, SentinelPool started a coroutine on initializing. so calling `close()` on SentinelPool is mandatory. especially when `create_sentinel_pool()` is the only one that can access "pool object" in case of an error.
That is why "Task was destroyed but it is pending!" happens.

This is how the last two lines of `create_sentinel_pool()` look like:

```python
await pool.discover()
return pool
```

I think it should be:
```python
try:
    await pool.discover()
except BaseException:
    pool.close()
    await pool.wait_closed()
    raise
```

**Comment by seandstewart** [comment]
This issue should be resolved as of #891 - please feel free to pull in the latest master and test to ensure this is the case.
