### ISSUE TITLE
Redis 6 Support

### ISSUE THREAD

**Issue by seandstewart** [aio-libs/aioredis-py#859]
We seem to have a few failing tests with the introduction of Redis 6.0 into the pipeline. Unfortunately the current output is not very helpful:

https://github.com/aio-libs/aioredis/runs/1468097976?check_suite_focus=true#step:11:5000

**Comment by Andrew-Chen-Wang** [comment]
Just to get this fixed quickly, some things to take note:

- `test_master__auth`: add `username` as a keyword parameter next to password in `conftest.py`'s `start_server` fixture. We may just need two different tests to make sure username and password are both checked.
- `test_auth`: the message is just different for Redis 6.0. You may want to test both the message for password and the one for username like aforementioned.
- `test_failover_command `: not entirely sure what's wrong
- `test_client_list `: Redis 6.2 added laddr. I'm not able to see that for myself, strangely enough... Set to `MOCK.Any`
- `test_client_list__unixsocket`: again, I couldn't see it, so I'm not sure what part of Redis instance could show this...
- `test_command_info`: it's just a Redis 6.0 addition

**Comment by seandstewart** [comment]
I'm going to remove Redis 6 from the pipeline until we've patched this so we can have a green build again on master.

**Comment by asvetlov** [comment]
> I'm going to remove Redis 6 from the pipeline until we've patched this so we can have a green build again on master.

The best you can do now

**Comment by seandstewart** [comment]
This issue should be resolved as of #891.
