### ISSUE TITLE
Obsolete examples?

### ISSUE THREAD

**Issue by JivanRoquet** [aio-libs/aioredis-py#921]
Following examples from the docs:

```python
import aioredis
redis = aioredis.from_url("redis://localhost", decode_responses=True)
```

Triggers an error message:

> **Module 'aioredis' has no 'from_url' member**

Similarly, still from the examples:

```python
import aioredis
redis = aioredis.Redis(host="localhost", decode_responsees=True)
```

Triggers this:

> **TypeError: __init__() got an unexpected keyword argument 'decode_responses'**

Are these examples obsolete?

**Comment by JivanRoquet** [comment]
Note: using aioredis version 1.3.1

**Comment by JivanRoquet** [comment]
Looks like the examples are actually the contrary of obsolete — it's the release that is

**Comment by seandstewart** [comment]
@JivanRoquet -

apologies here, you've hit us in the middle of getting our alpha release out the door for v2. We'll soon have a release and corresponding documentation update. For now, the examples in master should only be considered to work with the forthcoming release.
