### ISSUE TITLE
RuntimeWarning: coroutine 'Connection.disconnect' was never awaited

### ISSUE THREAD

**Issue by JivanRoquet** [aio-libs/aioredis-py#923]
When running tests that need mocking an `aioredis` connection, the following Runtime Warning gets triggered each time, and is mumbled together with some random code, which makes me think it looks like a fairly low-level bug:

```
tests/foo/test_foo_bar.py ...                                    [100%]
/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py:490:
RuntimeWarning: coroutine 'Connection.disconnect' was never awaited
  reversed(list(itertools.dropwhile(lambda x: x == 0, reversed(release))))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I'm not sure where that comes from but not from my own code, as I never mention a `disconnect` method anywhere.

```python
import pytest
import aioredis

from foo import api


@pytest.fixture
async def aioredis_conn():
    conn = await aioredis.Redis(
        decode_responses=True,
        single_connection_client=True,
        **config.redis_test_credentials
    )
    yield conn
    await conn.flushdb()


@pytest.fixture
def mock_redis_conn(mocker, redis_conn, aioredis_conn):
    mocker.patch("foo.api.aioredis_conn", new=aioredis_conn)

def test_foobar(mock_redis_conn):
    do_something()
```

Am I doing this approximately right? Is there any specific reason why this warning occurs?

**Comment by JivanRoquet** [comment]
The same warning as it gets captured by pytest:

```
=============================== warnings summary ===============================
tests/foo/test_foo_bar.py::test_api_online_features
  /usr/local/lib/python3.9/site-packages/aioredis/connection.py:681: RuntimeWarning: coroutine 'Connection.disconnect' was never awaited
    reader, writer = await asyncio.open_connection(
```

**Comment by Andrew-Chen-Wang** [comment]
This may be because async_timeout should be doing `async with` https://github.com/aio-libs/aioredis-py/blob/8ebc6e8c9c5ea293f1588769a89704fc9041d2f7/aioredis/connection.py#L680

**Comment by seandstewart** [comment]
I just isolated it, it's happening in `Connection.__delete__()`:

https://github.com/aio-libs/aioredis-py/blob/8ebc6e8c9c5ea293f1588769a89704fc9041d2f7/aioredis/connection.py#L630-L635

**Comment by Andrew-Chen-Wang** [comment]
The warning of something being un-awaited is still showing up in #924's tests

**Comment by JivanRoquet** [comment]
Thanks for the reactivity, folks
