### ISSUE TITLE
Error when setting client_name parameter

### ISSUE THREAD

**Issue by Yasu-San** [aio-libs/aioredis-py#937]
(Using Pre-Release)

When I set the client_name parameter of the Redis-Class, I get the following error:
`ConnectionError: Error setting client name`

Taking a look into the code it seems like there is a missing await.

I think
https://github.com/aio-libs/aioredis-py/blob/85d76474fdc609878706a4aecc47120827b290f2/aioredis/connection.py#L746
should be
```py
if str_if_bytes(await self.read_response()) != "OK":
```
instead.

**Comment by Andrew-Chen-Wang** [comment]
Good catch! Thanks!
