### ISSUE TITLE
using aioredis 2.0 client in multiple event loops

### ISSUE THREAD

**Issue by kiranpradeep** [aio-libs/aioredis-py#941]
I was trying migrate redis-py application to aioredis 2.0. It used redis client in multiple event loops. Below code sample is minimal example which works on 1.3.1, but fails on 2.0. It reports `RuntimeError: Event loop is closed`. How should we use the redis client across event loops?

```python
import aioredis
import asyncio

async def fun1(client):
    await client.set('key1', 'value')

async def fun2(client):
    await client.set('key2', 'value')

async def main():
    client = await aioredis.create_redis_pool("redis://localhost:6379") #aioredis:1.3.1 - SUCCESS
    #client = aioredis.Redis.from_url("redis://localhost:6379") #aioredis:2.0.0a1 - FAIL
    return client

client = asyncio.run(main())
asyncio.run(fun1(client))
asyncio.run(fun2(client))
```

> Traceback (most recent call last):
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/connection.py", line 848, in read_response
>     response = await self._parser.read_response()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/connection.py", line 499, in read_response
>     await self.read_from_socket()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/connection.py", line 463, in read_from_socket
>     buffer = await self._stream.read(self._read_size)
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/streams.py", line 684, in read
>     await self._wait_for_data('read')
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
>     await self._waiter
> RuntimeError: Task <Task pending name='Task-7' coro=<fun2() running at /mnt/d/kiran/src/git/elz/IoTEdge/main2.py:8> cb=[_run_until_complete_cb() at /home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/base_events.py:184]> got Future <Future pending> attached to a different loop
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/d/kiran/src/git/elz/IoTEdge/main2.py", line 17, in <module>
>     asyncio.run(fun2(client))
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/mnt/d/kiran/src/git/elz/IoTEdge/main2.py", line 8, in fun2
>     await client.set('key2', 'value')
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/client.py", line 1037, in execute_command
>     return await self.parse_response(conn, command_name, **options)
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/client.py", line 1053, in parse_response
>     response = await connection.read_response()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/connection.py", line 853, in read_response
>     await self.disconnect()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/site-packages/aioredis/connection.py", line 764, in disconnect
>     self._writer.close()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/streams.py", line 353, in close
>     return self._transport.close()
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/selector_events.py", line 700, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
>     self._check_closed()

>   File "/home/roots/miniconda3/envs/iotedge/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed

**Comment by Andrew-Chen-Wang** [comment]
Seems like it might not be possible in the current implementation. Does asyncio run in different threads? Still learning this code (and still learning the old code). Take a look at this 2.0.0a1 code:

Well when we await/initialize Redis we do https://github.com/aio-libs/aioredis-py/blob/cf908b60c57cb9d55a92befbbf9617fc79310194/aioredis/client.py#L875-L881

Then we need to get a connection: https://github.com/aio-libs/aioredis-py/blob/cf908b60c57cb9d55a92befbbf9617fc79310194/aioredis/connection.py#L1339-L1370

which uses `_lock: asyncio.Lock` It doesn't seem like we use a lock in the previous version: https://github.com/aio-libs/aioredis-py/blob/8a207609b7f8a33e74c7c8130d97186e78cc0052/aioredis/commands/__init__.py#L128-L157

Is it safe to say you can't use Redis in different asyncio event loops?

**Comment by agronholm** [comment]
> Is it safe to say you can't use Redis in different asyncio event loops?

That is generally the case with any async code. Locks don't change that since each lock would be tied to a specific event loop anyway.

**Comment by kiranpradeep** [comment]
Thanks all for the replies.

> That is generally the case with any async code. Locks don't change that since each lock would be tied to a specific event loop anyway.

To confirm the understanding, aioredis 1.3.1 working across eventloops (as shown in first post) is more of an aberration. I am closing this ticket. Humbly requesting to correct if the understanding is wrong.
