### ISSUE TITLE
using socket_timeout option leads to  ValueError (AIORedis 2.0)

### ISSUE THREAD

**Issue by ivan-antonyuck** [aio-libs/aioredis-py#951]
When running this code:
```
key = 'test'
redis = aioredis.Redis(connection_pool=aioredis.ConnectionPool.from_url(redis_url, socket_timeout=1))
await redis.get('key')
```

i'm getting the following exception:
```
...
  val = await redis.get(key)
  File "/usr/local/lib/python3.8/site-packages/aioredis/client.py", line 1034, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.8/site-packages/aioredis/connection.py", line 1361, in get_connection
    await connection.connect()
  File "/usr/local/lib/python3.8/site-packages/aioredis/connection.py", line 662, in connect
    raise ConnectionError(exc) from exc
aioredis.exceptions.ConnectionError: settimeout(): only 0 timeout is allowed on transport sockets
```

This might be because of double timeout handling - socket_timeout option used both in _connect (where the exception is generated) and in disconnect, read_response with async_timeout. Should those be two separate options, one for socket and another for async_timeout?

**Comment by Andrew-Chen-Wang** [comment]
In the middle of finals, so just questioning in advance: are you using latest on master or 2.0.0a1?

**Comment by ivan-antonyuck** [comment]
I've tested with both, and the trace i've included was in fact from lastest on master.

Just tested again with 2.0.0a1 from pypi, and it seems the same.

Here's the repo with test case: https://github.com/ivan-antonyuck/aioredis-timeout-test/tree/master

stacktrace for the pypi version:

```
/Users/antonyuck/.local/share/virtualenvs/aioredis_tests-k2Rjn665/bin/python /Users/antonyuck/work/projects/aioredis_tests/test.py
Traceback (most recent call last):
  File "/Users/antonyuck/.local/share/virtualenvs/aioredis_tests-k2Rjn665/lib/python3.8/site-packages/aioredis/connection.py", line 654, in connect
    await self._connect()
  File "/Users/antonyuck/.local/share/virtualenvs/aioredis_tests-k2Rjn665/lib/python3.8/site-packages/aioredis/connection.py", line 697, in _connect
    sock.settimeout(self.socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/trsock.py", line 188, in settimeout
    raise ValueError(
ValueError: settimeout(): only 0 timeout is allowed on transport sockets
```

**Comment by ivan-antonyuck** [comment]
I've tried removing setting the timeout on the transport socket in the connection constructor and it seems to work fine in case of redis server crash, at least.

**Comment by Andrew-Chen-Wang** [comment]
Good catch. This seems like an asyncio scenario that the PR port didn't catch. https://github.com/aio-libs/aioredis-py/blob/84baee589d10b279d98d8db7cf647237f38eb4ba/aioredis/connection.py#L689-L700

I believe the solution is to use `timeout=self.socket_timeout` here: https://github.com/aio-libs/aioredis-py/blob/84baee589d10b279d98d8db7cf647237f38eb4ba/aioredis/connection.py#L681-L686 Try adding that argument to `asyncio.open_connection` then remove this portion of code: https://github.com/aio-libs/aioredis-py/blob/84baee589d10b279d98d8db7cf647237f38eb4ba/aioredis/connection.py#L698-L700

**Comment by Andrew-Chen-Wang** [comment]
@seandstewart I think the bug here  is that sock is just used in this scope, unlike the `_connect` method in the [redis-py implementation](https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/connection.py#L166-L175) which sets the sock to the SocketBuffer. Is this just dead code then? https://github.com/aio-libs/aioredis-py/blob/84baee589d10b279d98d8db7cf647237f38eb4ba/aioredis/connection.py#L689-L706

**Comment by Andrew-Chen-Wang** [comment]
#960 fixes this hopefully. Please let me know if it does @ivan-antonyuck

**Comment by ivan-antonyuck** [comment]
Hi all. Sorry for the late answer. It seems that the problem persists, i've just tested using the same code from the first message

I aggree with @Andrew-Chen-Wang that sock.settimeout in _connect seems to be dead code and has to be removed.

**Comment by ivan-antonyuck** [comment]
https://github.com/aio-libs/aioredis-py/pull/986 added a pull request
