### ISSUE TITLE
"AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'" when using ssl enabled Redis object

### ISSUE THREAD

**Issue by itay-raveh** [aio-libs/aioredis-py#981]
Trying to use an ssl enabled connection results in an error reading "AttributeError: 'RedisSSLContext' object has no attribute 'wrap_bio'".

After some investigation it seems that wrap_bio is an attribute of ssl.SSLContext, which RedisSSLContext does not inheret, and that is used by both asyncio and uvloop.

This error occurs with every method of connection creation I've tried. (all 'from_url's and manual creation of Redis, ConnectionPool).

**Comment by Andrew-Chen-Wang** [comment]
Duplicate #975 Resolved on master
