### ISSUE TITLE
'aioredis' has no attribute 'from_url'

### ISSUE THREAD

**Issue by czf0613** [aio-libs/aioredis-py#987]
Hello, I have some problems when using this aio-lib.
I am using python 3.9 in my project, when I am going to initialize a redis connection using "aioredis.from_url("redis://myhost.com")".
I just follow the instructions on your website but does not work.

Looking forward to official solution, thanks a million.

**Comment by Andrew-Chen-Wang** [comment]
Apologies. Our docs for installation are not properly updated. You'll need to install from 2.0.0a1 or our recommended method (for now) is to install from a specific commit. Ref: #930

**Comment by czf0613** [comment]
Thanks a lot, I have already solved this question.
