### ISSUE TITLE
watch not work

### ISSUE THREAD

**Issue by RonaldinhoL** [aio-libs/aioredis-py#995]
``` python
redis_pool = await aioredis.create_redis_pool('redis://localhost')
await redis_pool.delete("xxx")

async def write(i):
    await redis_pool.watch("xxx")
    v = int(await redis_pool.get("xxx", encoding="utf8"))
    v += 1
    tr = redis_pool.multi_exec()
    tr.set("xxx", v)
    r = await tr.execute()
    print(f"set to {v}")

await redis_pool.set("xxx", 0)
tasks = []
for i in range(0, 10):
    t = asyncio.create_task(write(i))
    tasks.append(t)
await asyncio.gather(*tasks)
print(await redis_pool.get("xxx") )
```

i did not recieve a watch error, is there anything wrong?

**Comment by Andrew-Chen-Wang** [comment]
@RonaldinhoL maybe don't create tasks? Like:

```python
await asyncio.gather(*[write(i) for i in range(0, 10)])
```

Not sure though.

**Comment by seandstewart** [comment]
The `WATCH` command is server-side. Redis is single-threaded (mostly) which means each command is processed in-turn. 

The Redis client implementation creates an in-memory buffer and does not flush the commands to the server until `execute` is called, which helps guarantee atomicity as well as better performance (less IO loops). Another side-effect is less risk of overlapping mutations from a single client.

A better way to test this would be to start and watch a transaction with one connection and try to change the key with another connection within the same task.

**Comment by RonaldinhoL** [comment]
> The `WATCH` command is server-side. Redis is single-threaded (mostly) which means each command is processed in-turn.
> 
> The Redis client implementation creates an in-memory buffer and does not flush the commands to the server until `execute` is called, which helps guarantee atomicity as well as better performance (less IO loops). Another side-effect is less risk of overlapping mutations from a single client.
> 
> A better way to test this would be to start and watch a transaction with one connection and try to change the key with another connection within the same task.

in 2.0alpha and other redis lib, watch must in pipe, but in aioredis 1.3 if watch in muti/exec it wil throw a exception.
how can i to write a Optimistic locking in aioredis1.3?

**Comment by abrookins** [comment]
I'm afraid the current maintainers of this library can't support the 1.x series -- we don't have enough experience with that codebase and have taken the library in a new direction (2.0).

>in 2.0alpha and other redis lib, watch must in pipe, but in aioredis 1.3 if watch in muti/exec it wil throw a exception.

You didn't mention that your original code threw an exception -- was that the case? If you didn't get a watch error, then your code never triggered the condition. You should start one script running a thread that repeatedly writes to a key, and start another script that continually tries to read a value and change it, using `watch()`. That should eventually trigger the condition. This is more or less what Sean already suggested.

And, let me clear up how this works with redis-py/aioredis-py 2.0, just in case you aren't aware (though you very may well be!). There is mildly confusing terminology in the redis-py API that we've carried over, which is that calling `pipeline()` creates a MULTI/EXEC transaction, while calling `pipline(transaction=False)` creates a true "pipeline." A Redis pipeline is a set of commands buffered on the client-side until you execute the pipeline, which Redis then runs non-atomically, i.e. allowing other commands to run in between your commands.

WATCH only applies to MULTI/EXEC transaction, which, again, is what `pipeline()` creates. The redis-py docs show how WATCH works in detail:

```python
>>> with r.pipeline() as pipe:
...     while True:
...         try:
...             # put a WATCH on the key that holds our sequence value
...             pipe.watch('OUR-SEQUENCE-KEY')
...             # after WATCHing, the pipeline is put into immediate execution
...             # mode until we tell it to start buffering commands again.
...             # this allows us to get the current value of our sequence
...             current_value = pipe.get('OUR-SEQUENCE-KEY')
...             next_value = int(current_value) + 1
...             # now we can put the pipeline back into buffered mode with MULTI
...             pipe.multi()
...             pipe.set('OUR-SEQUENCE-KEY', next_value)
...             # and finally, execute the pipeline (the set command)
...             pipe.execute()
...             # if a WatchError wasn't raised during execution, everything
...             # we just did happened atomically.
...             break
...        except WatchError:
...             # another client must have changed 'OUR-SEQUENCE-KEY' between
...             # the time we started WATCHing it and the pipeline's execution.
...             # our best bet is to just retry.
...             continue
```

So you create a "pipeline" object (a transaction). When you call `watch()` on the pipeline, doing so turns off buffered execution mode and instead runs your command immediately, so you can get a value that your computation depends on.

You need to call `multi()` to put the pipeline back into buffered mode, queue up the commands you want to run in the transaction, and finally call `execute()`. You'll get a watch error if the watched key has changed between the time you called `watch()` and the time Redis executes the transaction. Or in other words, the optimistic concurrency you desire.

**Comment by RonaldinhoL** [comment]
year, finally i decide upgrade to 2.0,  my problem was solved and can keep the same code style to other lib, thank you very much!
