### ISSUE TITLE
Doubt about Lock

### ISSUE THREAD

**Issue by izaguerreiro** [aio-libs/aioredis-py#999]
Hello everyone, everything good?

Do you have any predictions for the date of the new version that will have [this](https://github.com/aio-libs/aioredis-py/blob/master/aioredis/lock.py#L13) Lock class?

I'm implementing Lock that is in version 1.3.1, but I couldn't understand how it works, does it lock the entire Redis? Because at no time do I tell you which key to lock.

Thanks

**Comment by Andrew-Chen-Wang** [comment]
We'll push out version 2.0.0 soon as in hopefully within next week. Closing as this is about 1.3.1 that we won't support.
